// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/aggregation/results": {
            "get": {
                "description": "Get network-wide aggregated batches with validator contributions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "aggregation"
                ],
                "summary": "Aggregation results",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of results (default 20)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.FinalizedBatch"
                            }
                        }
                    }
                }
            }
        },
        "/batches/finalized": {
            "get": {
                "description": "Get Level 1 (local) or Level 2 (aggregated) finalized batches",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "batches"
                ],
                "summary": "Finalized batches",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Batch level (1 or 2, default both)",
                        "name": "level",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Specific epoch ID",
                        "name": "epoch_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of batches to retrieve (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.FinalizedBatch"
                            }
                        }
                    }
                }
            }
        },
        "/dashboard/summary": {
            "get": {
                "description": "Get pre-aggregated dashboard metrics from state-tracker",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dashboard"
                ],
                "summary": "Dashboard summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DashboardSummary"
                        }
                    }
                }
            }
        },
        "/epochs/timeline": {
            "get": {
                "description": "Get epoch progression with phases and batch status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "epochs"
                ],
                "summary": "Epochs timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of epochs (default 50)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.EpochInfo"
                            }
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check if the API and Redis connection are healthy",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/pipeline/overview": {
            "get": {
                "description": "Get pipeline metrics from pre-aggregated data",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pipeline"
                ],
                "summary": "Pipeline overview (legacy support)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/queues/status": {
            "get": {
                "description": "Get real-time queue depths and processing rates",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "queues"
                ],
                "summary": "Queue status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/main.QueueStatus"
                            }
                        }
                    }
                }
            }
        },
        "/stats/daily": {
            "get": {
                "description": "Get pre-aggregated 24-hour statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Daily statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DailyStats"
                        }
                    }
                }
            }
        },
        "/stats/hourly": {
            "get": {
                "description": "Get pre-aggregated hourly statistics",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "stats"
                ],
                "summary": "Hourly statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address",
                        "name": "market",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of hours to retrieve (default 24)",
                        "name": "hours",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HourlyStats"
                        }
                    }
                }
            }
        },
        "/timeline/recent": {
            "get": {
                "description": "Get recent events from timeline sorted sets with enriched metadata",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "timeline"
                ],
                "summary": "Recent timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Event type (submission, validation, epoch, batch)",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Minutes to look back (default 5)",
                        "name": "minutes",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "Include detailed metadata from Redis (default true)",
                        "name": "include_metadata",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.EnhancedTimelineResponse"
                        }
                    }
                }
            }
        },
        "/vpa/epoch/{epochID}": {
            "get": {
                "description": "Get priority assignment and submission status for a specific epoch. Returns combined priority and submission information including priority details and submission details if available.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vpa"
                ],
                "summary": "Get VPA status for specific epoch",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Epoch ID",
                        "name": "epochID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Protocol state identifier (defaults to configured protocol)",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address (defaults to configured market)",
                        "name": "market",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "VPA epoch status with priority and submission information",
                        "schema": {
                            "$ref": "#/definitions/main.VPAEpochStatusResponse"
                        }
                    },
                    "404": {
                        "description": "Epoch not found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/vpa/stats": {
            "get": {
                "description": "Get aggregated VPA statistics including total priority assignments, submission counts (success/failed), success rates, and 24-hour activity counts.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vpa"
                ],
                "summary": "Get VPA statistics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier (defaults to configured protocol)",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address (defaults to configured market)",
                        "name": "market",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Aggregated VPA statistics",
                        "schema": {
                            "$ref": "#/definitions/main.VPAStatsResponse"
                        }
                    }
                }
            }
        },
        "/vpa/timeline": {
            "get": {
                "description": "Get priority assignment and submission timeline. Returns recent priority assignments and/or submissions ordered by timestamp (most recent first).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vpa"
                ],
                "summary": "Get VPA timeline",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Protocol state identifier (defaults to configured protocol)",
                        "name": "protocol",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Data market address (defaults to configured market)",
                        "name": "market",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Timeline type: 'priority', 'submission', or 'both' (default: 'both')",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Number of entries to retrieve per timeline type (default: 50, max: 1000)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "VPA timeline with priority and/or submission entries",
                        "schema": {
                            "$ref": "#/definitions/main.VPATimelineResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DailyStats": {
            "type": "object",
            "properties": {
                "hourly_breakdown": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "summary": {
                    "type": "object",
                    "additionalProperties": true
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.DashboardSummary": {
            "type": "object",
            "properties": {
                "current_status": {
                    "description": "Real-time status (epoch, queues)",
                    "type": "object",
                    "additionalProperties": true
                },
                "participation_stats": {
                    "description": "24h participation/inclusion metrics",
                    "type": "object",
                    "additionalProperties": true
                },
                "recent_activity": {
                    "description": "1m and 5m activity",
                    "type": "object",
                    "additionalProperties": true
                },
                "system_metrics": {
                    "description": "Rates, totals, current counts (includes VPA metrics)",
                    "type": "object",
                    "additionalProperties": true
                },
                "timestamp": {
                    "type": "string"
                },
                "validator_id": {
                    "type": "string"
                },
                "vpa_metrics": {
                    "description": "VPA-specific metrics (priority assignments, submissions)",
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "main.EnhancedTimelineEvent": {
            "type": "object",
            "properties": {
                "entity_id": {
                    "type": "string"
                },
                "metadata": {
                    "$ref": "#/definitions/main.TimelineEventMetadata"
                },
                "time": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "integer"
                }
            }
        },
        "main.EnhancedTimelineResponse": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "events": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.EnhancedTimelineEvent"
                    }
                },
                "minutes": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.EpochInfo": {
            "type": "object",
            "properties": {
                "data_market": {
                    "type": "string"
                },
                "duration": {
                    "type": "integer"
                },
                "epoch_id": {
                    "type": "string"
                },
                "level1_batch_exists": {
                    "type": "boolean"
                },
                "level2_batch_exists": {
                    "type": "boolean"
                },
                "phase": {
                    "description": "\"submission\", \"finalization\", \"aggregation\", \"complete\"",
                    "type": "string"
                },
                "start_time": {
                    "type": "integer"
                },
                "status": {
                    "description": "\"open\", \"closed\"",
                    "type": "string"
                }
            }
        },
        "main.FinalizedBatch": {
            "type": "object",
            "properties": {
                "epoch_id": {
                    "type": "string"
                },
                "ipfs_cid": {
                    "type": "string"
                },
                "level": {
                    "description": "1 for local, 2 for aggregated",
                    "type": "integer"
                },
                "merkle_root": {
                    "type": "string"
                },
                "project_count": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "integer"
                },
                "type": {
                    "description": "\"local\" or \"aggregated\"",
                    "type": "string"
                },
                "validator_count": {
                    "description": "Level 2 only",
                    "type": "integer"
                },
                "validator_id": {
                    "description": "Level 1 only",
                    "type": "string"
                },
                "validator_ids": {
                    "description": "Level 2 only",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.HourlyStats": {
            "type": "object",
            "properties": {
                "hours": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": true
                    }
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.QueueStatus": {
            "type": "object",
            "properties": {
                "depth": {
                    "type": "integer"
                },
                "queue_name": {
                    "type": "string"
                },
                "status": {
                    "description": "\"empty\", \"healthy\", \"moderate\", \"high\", \"critical\"",
                    "type": "string"
                }
            }
        },
        "main.TimelineEventMetadata": {
            "type": "object",
            "properties": {
                "data_market": {
                    "type": "string"
                },
                "epoch_id": {
                    "type": "string"
                },
                "event_type": {
                    "description": "\"submission\", \"validation\", \"batch\", \"epoch\"",
                    "type": "string"
                },
                "is_enhanced": {
                    "description": "Whether entity ID uses new enhanced format",
                    "type": "boolean"
                },
                "peer_id": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "slot_id": {
                    "type": "string"
                },
                "submission_type": {
                    "description": "\"snapshot\", \"validation\"",
                    "type": "string"
                },
                "validator_id": {
                    "type": "string"
                }
            }
        },
        "main.VPAEpochStatusResponse": {
            "type": "object",
            "properties": {
                "epoch_id": {
                    "type": "string"
                },
                "status": {
                    "description": "Combined priority and submission status",
                    "type": "object",
                    "additionalProperties": true
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.VPAStatsResponse": {
            "type": "object",
            "properties": {
                "stats": {
                    "description": "Contains priority assignments, submissions, success rates, etc.",
                    "type": "object",
                    "additionalProperties": true
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "main.VPATimelineResponse": {
            "type": "object",
            "properties": {
                "timeline": {
                    "description": "Contains \"priority_timeline\" and/or \"submission_timeline\"",
                    "type": "object",
                    "additionalProperties": true
                },
                "timestamp": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DSV Pipeline Monitor API (Direct Redis)",
	Description:      "Monitoring API that reads pre-aggregated data from state-tracker worker",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
